LooksterWeb/Controllers/LegalController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LooksterWeb.Controllers
{
    public class LegalController : Controller
    {
        // GET: Legal
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult TermsOfUse()
        {
            ViewBag.InfoText = "  ";
            return View();
        }
        public ActionResult PrivacyPolicy()
        {
            ViewBag.InfoText = "  ";
            return View();
        }
    }
}

LooksterWeb/Controllers/TransactionsController.cs
using LooksterServices;
using LooksterWeb.Core;
using LooksterWeb.Core.ActionToken;
using LooksterWeb.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LooksterWeb.Controllers
{
    public class TransactionsController : Controller
    {
        private looksterdbEntities db = new looksterdbEntities();
        // GET: Transactions
        public ActionResult Index()
        {
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Error()
        {
            return View("ErrorTransaction");
        }
        public ActionResult Success()
        {
            return View("SuccessTransaction");
        }
        [HttpGet]
        public ActionResult ResetPassword(string Email,string ActionTokenData)
        {
            try
            {
                string storedToken = (string)CacheProvider.Instance.GetCacheObject(Email, ActionTokenReasons.ResetPassword);
                TokenSecureService.Instance.DecodeToken(ref ActionTokenData);
                ActionTokenGetModel actionToken = db.ActionTokenGet(ActionTokenData).FirstOrDefault();
                if (storedToken != null && 
                    storedToken == ActionTokenData &&
                    actionToken.IsExpired > 0 && 
                    actionToken.Action == (int)ActionTokenReasons.ResetPassword)
                {
                    return View(new ResetPasswordModel() { Email = Email });
                }
                return View("ErrorTransaction");
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return View("ErrorTransaction");
            }
            
        }

        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            try
            {
                string storedToken = (string)CacheProvider.Instance.GetCacheObject(model.Email, ActionTokenReasons.ResetPassword);
                ActionTokenGetModel actionToken = db.ActionTokenGet(storedToken).FirstOrDefault();
                if (storedToken != null &&
                    actionToken != null &&
                    actionToken.IsExpired > 0 &&
                    actionToken.Action == (int)ActionTokenReasons.ResetPassword)
                {
                        db.UpdatePasswordByUserId(actionToken.UserId, model.Password);
                }
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return View("ErrorTransaction");
            }

            //db.UpdatePasswordByUserId()
            //ViewBag.InfoText = "  ";
            return View("SuccessTransaction");
        }

        [HttpGet]
        public ActionResult ConfirmRegistrationd(long? id)
        {
            try
            {
                db.ConfirmRegistration(id);

                return View();
            }
            catch (Exception ex)
            {
                Debug.WriteLine(ex.Message);
                return View("ErrorTransaction");
            }
            
        }
    }
}

LooksterWeb/Views/Transactions/ConfirmRegistrationd.cshtml
@{
    ViewBag.Title = "View";
}

<div class="container-fluid">
    <div class="row">
        <div id="contact-form" class="col-md-10 col-md-offset-1">
            @*<div class="col-md-2 col-md-offset-5" style="margin-top:20px;">
                <img class="img-responsive" alt="lookster logo" src="~/Content/images/logo.png" />
            </div>*@


            <h1 class="text-center" style="color:#334D5C; font-weight: bold;">Регистрация прошла успешно!</h1>
            <h3 class="text-center" style="color: #45b29d;  font-weight: bold; margin-top: 15px;">Спасибо, что выбрали Looksterapp! Мы рады, что вы с нами.</h3>
            <ul class="col-md-12 text-center" style="margin-top:50px;">
                <p class="text-center" style="color:grey;">По всем вопросам обращайтесь на <a href="support@looksterapp.info">  support@looksterapp.info</a></p>
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Политика конфиденциальности", "PrivacyPolicy", "Legal")</li>
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Условия использования", "TermsOfUse", "Legal")</li>
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Главная", "Index", "Home")</li>

            </ul>
        </div>
    </div>
</div>

<div class="container-fluid">
    <div class="row">
        @*<div class="col-md-2 col-md-offset-5" style="margin-top:30px;">
            <i class="fa fa-user-plus" style="color: #45b29d; width:100%;"></i>
        </div>*@
       
       
    </div>
</div>

LooksterWeb/Views/Transactions/ErrorTransaction.cshtml
@{
    ViewBag.Title = "ErrorTransaction";
}

<script>
    document.getElementById("main-body").style.background = "rebeccapurple";
    window.onload = function () {
        var redirectUrl = "document.location.href=" + "'/Home';";
        setTimeout(redirectUrl, 3000);
    }
</script>
<h2 class="text-center" style="color:red;">ErrorTransaction</h2>

LooksterWeb/Views/Transactions/ResetPassword.cshtml
@model LooksterWeb.Models.ResetPasswordModel
@{
    ViewBag.Title = "View";
}


<div class="container-fluid">
    <div class="row">
        <div id="contact-form" class="col-md-10 col-md-offset-1 ">
            <div class="col-md-2 col-md-offset-5 col-sm-2 col-sm-offset-5 col-xs-4 col-xs-offset-4" style="margin-top:20px; margin-bottom:20px;">
                <img class="img-responsive" alt="lookster logo" src="~/Content/images/logo.png" />
            </div>

            @using (Ajax.BeginForm("ResetPassword", "Transactions", null, new AjaxOptions { HttpMethod = "Post", InsertionMode = InsertionMode.ReplaceWith, UpdateTargetId = "contact-form" }, new { @class = "col-md-4 col-md-offset-4" }))
            {
                @Html.HiddenFor(model => model.Email);
                <h1 class="text-center" style="color:#334D5C; font-weight: bold; margin-bottom: 30px;">Смена пароля</h1>
                <div class="">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @type = "password", @placeholder = "Пароль", @style = "border: none; border-bottom: 1px solid grey;", @id = "password1" } })
                    <span class="error"> @Html.ValidationMessageFor(model => model.Password)</span>
                </div>
                <div class="">
                    @Html.EditorFor(model => model.RepeatPassword, new { htmlAttributes = new { @type = "password", @required = "true", @placeholder = "Повторить пароль", @style = "border: none; border-bottom: 1px solid grey;", @id = "password2" } })
                    <span class="error">@Html.ValidationMessageFor(model => model.RepeatPassword)</span>
                </div>
                <br />
                <div>
                    <p id="error_input" style="color:red; font-weight:bold;"></p>
                </div>
                
                <div class="width:100%;">
                    <input type="submit" class="orange-button" value="Сохранить" style="width:100%; " onclick="return validateForm()">
                    <p class="text-center" style="color:grey;">По всем вопросам обращайтесь на <a href="support@looksterapp.info">  support@looksterapp.info</a></p>
                </div>
            
            }
            <ul class="col-md-12 text-center" style="margin-top:50px;" >
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Политика конфиденциальности", "PrivacyPolicy", "Legal")</li>
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Условия использования", "TermsOfUse", "Legal")</li>
                <li style="display:inline; padding-right: 20px;">@Html.ActionLink("Главная", "Index", "Home")</li>

            </ul>
        </div>
    </div>
</div>

<script>
    function validateForm () {

    var password1 = document.getElementById('password1');
    var password2 = document.getElementById('password2');
    var reg = /(?!^[0-9]*$)(?!^[a-zA-Z]*$)^([a-zA-Z0-9]{8,255})$/;
    if (password1.value !== password2.value) {
        document.getElementById("error_input").innerHTML = "Пароли должны быть одинаковыми!";
        return false;
        }

    if (!reg.test(password1.value) || !reg.test(password2.value)) {
        document.getElementById("error_input").innerHTML = "Пароль должен содержать буквы и цифры, минимум 8 символов.";
        return false;
    } 
    
    }
 

</script>

LooksterWeb/Views/Transactions/SuccessTransaction.cshtml
@{
    ViewBag.Title = "SuccessTransaction";
}

<script>
document.getElementById("main-body").style.background = "orange";
	window.onload = function () {
		var redirectUrl = "document.location.href=" + "'/Home';";
		setTimeout(redirectUrl, 3000);
	}
</script>
<h2 class="text-center" style="color:white;">Success Transaction</h2>